version: "3.6"

services:
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
  hasura:
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:admin@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 60
      HASURA_GRAPHQL_NO_OF_RETRIES: 30
    volumes:
        - ./FluentGraphQL.Tests/hasura/migrations:/hasura-migrations
        - ./FluentGraphQL.Tests/hasura/metadata:/hasura-metadata
  tests:
    build:
        context: .
        dockerfile: ./FluentGraphQL.Tests/.Dockerfile
    depends_on:
    - "hasura"
volumes:
  db_data: