version: "3"

services:    
    tests:
        build:
            context: .
            dockerfile: ./FluentGraphQL.Tests/.Dockerfile
        depends_on:
            - "hasura"
    hasura:
        image: hasura/graphql-engine:v1.3.2
        ports:
            - "127.0.0.1:8080:8080"
        depends_on:
            - "postgres"
        volumes:
            - ./FluentGraphQL.Tests/hasura/migrations:/hasura-migrations
            - ./FluentGraphQL.Tests/hasura/metadata:/hasura-metadata
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://admin:admin@127.0.0.1:5432/fluent_graphql
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
            HASURA_GRAPHQL_NO_OF_RETRIES: 3
        env_file:
            - ./FluentGraphQL.Tests/hasura/.env
    postgres:
        image: postgres:12.2
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: fluent_graphql
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:
        driver: local