name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: docker-compose -f docker-compose.yml up -d
    - name: Display container status
      run: docker-compose ps
    - name: Display docker logs
      run: docker-compose logs 
    - name: Wait for hasura migrations
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - name: Display hasura logs
      run: docker-compose logs hasura
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
    - name: Display hasura logs
      run: docker-compose logs hasura